### ISSUE TITLE
Transparent background on View window.

### ISSUE THREAD

**Issue by ApostolosB** [mkeeter/antimony#113]
This happens on Linux with wayland and an intel i915 card. Tried on 2 compositors. Weston and on enlightenment from git.

wayland 1.8.1
qt 5.5

I set QT_QPA_PLATFORM=wayland-egl

On Xwayland it works as it should.

**Comment by mkeeter** [comment]
Interesting.  Are you running open-source or binary drivers?

**Comment by ApostolosB** [comment]
Open. Intel doesn't have closed drivers for its cards on linux so i can't test with a different driver. 

One more thing i noticed -in case it can give you a clue- is that if i select View>Height map it creates a black background just around the object and leaves the rest of the window transparent.

**Comment by mkeeter** [comment]
Okay, that's pretty funky.  Can you mess with the clear color [here](https://github.com/mkeeter/antimony/blob/develop/app/src/ui/viewport/viewport.cpp#L587-L588) and see if that makes a difference?

**Comment by ApostolosB** [comment]
Ok. Changed  glClearColor(0.0, 0.0, 0.0, 0.0); to  glClearColor(0.0, 0.0, 0.0, 1.0); and now i get a black background. 

Didn't test if it breaks something else but seems to work on wayland (both compositors) and xwayland.

So yeah this fixes it.

**Comment by mkeeter** [comment]
Aha!  For some reason, I was under the impression that the last value was a depth clearing value; it's actually alpha, so that makes perfect sense.  Thanks for doing that test -- would you mind opening up a pull request into `develop` that makes this change?

**Comment by mkeeter** [comment]
Fixed by #115
