### ISSUE TITLE
.node files installation

### ISSUE THREAD

**Issue by sagitter** [mkeeter/antimony#114]
Hi all,

what does https://github.com/mkeeter/antimony/tree/develop/py/nodes directory contain?
And where all ```.node``` files should be installed in Linux system to be useful for ```Antimony```?

**Comment by mkeeter** [comment]
The nested lists of `.node` files are populated into the Add menu; they're a bunch of Python scripts that define basic shapes and transforms.

You shouldn't need to do anything with these folders manually; Antimony knows where to find them (when running the executable `$BINDIR/antimony`, it will search `$BINDIR/sb/nodes`). 

They should be installed with (`sudo`) `make install` into `/usr/local/bin/sb/nodes` (with the executable ending up in `/usr/local/bin/Antimony`); if you're just running `Antimony` from the build directory, they should be in `$BUILDDIR/app/sb/nodes`.  Both of these copying operations happen automatically in the build scripts.

**Comment by sagitter** [comment]
Hi,

for an official packaging it's not a good idea, i think.

Could they be stored under /usr/share and redirect antimony searching against new location?

Thanks.

**Comment by mkeeter** [comment]
The relevant part of the install script is [here](https://github.com/mkeeter/antimony/blob/develop/app/app.pro#L42-L48).

We already search for nodes in two places: [`bundledNodePath`](https://github.com/mkeeter/antimony/blob/develop/app/src/app/app.cpp#L334-L361) and [`userNodePath`](https://github.com/mkeeter/antimony/blob/develop/app/src/app/app.cpp#L363-L369) (which uses the [QStandardPaths](http://doc.qt.io/qt-5/qstandardpaths.html) class, producing `~/.local/share/Antimony` on Linux).

These two locations are used [here](https://github.com/mkeeter/antimony/blob/develop/app/src/ui/main_window.cpp#L172-L19) in `populateNodeMenu`.

Want to propose a new organization structure and submit a PR?

**Comment by sagitter** [comment]
Installing nodes paths under ```/usr/share``` could already be a good choice; however, i wouldn't be able to change ```Antimony``` Qt code.

Thanks.

**Comment by sagitter** [comment]
>We already search for nodes in two places: bundledNodePath and userNodePath (which uses the QStandardPaths class, producing ~/.local/share/Antimony on Linux).

How do i set ```QStandardPaths::AppDataLocation``` to ```/usr/share/<appname>``` ?

**Comment by astronouth7303** [comment]
@sagitter You can't modify them.

The correct thing to do is to use the full directory list for `QStandardPaths::AppDataLocation`. This is `~/.local/share/<APPNAME>`, `/usr/local/share/<APPNAME>`, and `/usr/share/<APPNAME>`.

**Comment by mkeeter** [comment]
Interesting -- that would involve calling `QStandardPaths::standardLocations` instead of just `QStandardPaths::writableLocation`, but seems perfectly reasonable.

**Comment by sagitter** [comment]
@astronouth7303,

do you mean

```nodes_folder.path = /usr/share/Antimony/nodes```
```nodes_folder.files = /usr/share/Antimony/nodes/*```

?

**Comment by astronouth7303** [comment]
Not exactly. Refactor to loop through a `QStringList`, as returned from the previously-mentioned `QStandardPaths::standardLocations()`.

This will do the Right Thing for every platform, with all the possible locations to look in.

**Comment by sagitter** [comment]
> @sagitter You can't modify them.
The correct thing to do is to use the full directory list for QStandardPaths::AppDataLocation. This is ~/.local/share/<APPNAME>, /usr/local/share/<APPNAME>, and /usr/share/<APPNAME>.

Please, can you help me to patch this variable?

**Comment by mkeeter** [comment]
Okay, this should be fixed in the `release/0.9.2b` branch
(to be merged into `develop` after the release is complete).

Here are the paths that are searched by default:
<img width="476" alt="screen shot 2016-07-06 at 7 19 57 pm" src="https://cloud.githubusercontent.com/assets/745333/16637661/ab6b9c72-43ae-11e6-831d-b331715239c7.png">
(where `Filtered` paths are the ones that actually exist)

**Comment by ApostolosB** [comment]
I fresh installed latest git and the ./local/share/nodes dir wasn't created. Is it a known issue? (Linux)
