### ISSUE TITLE
Error when trying to add anything

### ISSUE THREAD

**Issue by TheThirdOne** [mkeeter/antimony#117]
Whenever I use something in the add menu, this error shows up:
```
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)
```

**Comment by mkeeter** [comment]
Are you running on Linux under gcc 4.8?

If so, please follow the instructions in [BUILDING.md](https://github.com/mkeeter/antimony/blob/develop/BUILDING.md#linux) to install gcc 4.9, which has support for `std::regex`. (gcc 4.8 just pretends to support it, then fails at runtime -- it's great!)

**Comment by TheThirdOne** [comment]
Yeah, that was the problem. I'm not sure why I skipped over that section in the build instructions.

**Comment by TheThirdOne** [comment]
Thanks
