### ISSUE TITLE
Exporting a heightmap crashes the program

### ISSUE THREAD

**Issue by tenedor** [mkeeter/antimony#119]
Steps to reproduce:
- create a `Heightmap (.png)` export node and connect an input shape
- click the `Export` button that appears
- select a resolution and file location and hit `Save`

A progress bar dialog pops up that says "Exporting..." but within a few seconds the program crashes. An empty .png file will be created in the intended file location.

I am running OS X Yosemite 10.10.2 using the Antimony 0.9.0 direct-download application.

Here's a [crash log](https://gist.github.com/tenedor/da05aa943276872c9e06).

**Comment by mkeeter** [comment]
I've added debug print statements to the png export and put a debug build online [here](http://www.mattkeeter.com/misc/Antimony.dmg).

Can you try to reproduce the issue with this build?

Running it from the Terminal (i.e. by calling `./Antimony.app/Contents/MacOS/Antimony`) will print out `libpng`'s error messages.

**Comment by tenedor** [comment]
Here's the [https://gist.github.com/tenedor/67cc7f41539687e7f829](crash log) for running it with the debug build. Was it supposed to print libpng errors to terminal though? There was only a single line of output in my terminal:
```
$ ~/Documents/Antimony.app/Contents/MacOS/Antimony 
zsh: illegal hardware instruction  ~/Documents/Antimony.app/Contents/MacOS/Antimony
```

**Comment by mkeeter** [comment]
Interesting.  Can you open up Activity Monitor while Antimony is running and paste in the list of open files and ports?

I'm suspicious that it's getting confused between the system's `libpng` (in `/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib`) and the bundled `libpng`, but not sure why this doesn't happen on my machine.

**Comment by mkeeter** [comment]
Also, I've posted another debug build at the [same URL](http://mattkeeter.com/misc/Antimony.dmg).

It should print out a debug statement with information about the png export, e.g.
```
~/code/antimony/build-release $ ./app/Antimony.app/Contents/MacOS/Antimony 
Exporting a 510 x 510 image to '/Users/mkeeter/Desktop/out.png' with pixel pointer 0x7ffb059a4200
```

**Comment by tenedor** [comment]
Here's the [https://gist.github.com/tenedor/8f58ee3dfa3e14feda72](list of open files and the new crash log). Terminal output was

```
$ ~/Documents/Antimony.app/Contents/MacOS/Antimony
Exporting a 510 x 510 image to '/Users/daniel/Documents/Harvard/Semester 7/MAS 863/keyset.png' with pixel pointer 0x7ff47a374000
zsh: illegal hardware instruction  ~/Documents/Antimony.app/Contents/MacOS/Antimony
```

**Comment by mkeeter** [comment]
This is getting very mysterious.

I was hopeful that the spaces in the file path were causing the crash, but tried it locally and nothing went wrong.

Here's the next step I'd like you to try:
Install `libpng` with [Homebrew](http://brew.sh/) (i.e. `brew install libpng`), then copy the newly-installed `/usr/local/lib/libpng16.16.dylib` into the Antimony app bundle (`Antimony.app/Contents/Frameworks/libpng16.16.dylib`), replacing the existing library in that location.

This should tell us if there's something wrong with the version of libpng that I'm distributing.

Thanks for your patience in debugging this issue.  It's hard when I can't reproduce something locally, so I appreciate your remote-debugging help.

**Comment by mkeeter** [comment]
The relevant line when you disassemble `libpng` is

```
000000000001df19        bextrl  %eax, %r12d, %eax
```

A bit of searching finds `bextrl` is probably part of the [Bit Manipulation Instruction Set 1](https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets#BMI1_.28Bit_Manipulation_Instruction_Set_1.29), though I can't find it anywhere other than compiler test suites...

Could it be that compiling `libpng` on my machine has chosen instructions that aren't available on your CPU?

**Comment by mkeeter** [comment]
I've put up a new testing build at the [same URL](http://mattkeeter.com/misc/Antimony.dmg) that doesn't have the `bextrl` calls.  Maybe this will resolve your issue?

**Comment by tenedor** [comment]
Thanks for all your help @mkeeter! It looks like it'll be a couple days before I can get back to you with more info - as of two hours ago my computer's hard disk appears permanently broken (the computer's four years old). I'll get back to this once I fix that.

**Comment by tenedor** [comment]
Fantastic, the new code succeeds - I can now export height maps. (It worked without any updates to libpng.) Thanks!

**Comment by mkeeter** [comment]
Cool, I'll switch to the friendlier libpng in the released disk image.  Thanks for you help in debugging this!
