### ISSUE TITLE
Antimony crash

### ISSUE THREAD

**Issue by jwcrawley** [mkeeter/antimony#135]
Greetings,

I was able to make Antimony crash with the following error:

     antimony: ../../../lib/graph/src/datum.cpp:213: std::string Datum::formatLink(const Datum*) const: Assertion `false' failed.
     Aborted

I did this by doing the following:
     1. Add<2D<Circles<Circle(center)
     2. Add<2D<Rectangles<Rectangle(center)
     3. Connect Output(circle, radius) to Input(Rectangle, height)

Sincerely,
Josh Conway

Edit:
System: Ubuntu 15.04, Qt 5.5.1, antimony commit# 15f82ed

**Comment by mkeeter** [comment]
Confirmed, I'll check it out.

**Comment by mkeeter** [comment]
Okay, should be fixed.

**Comment by jwcrawley** [comment]
That seems to have fixed it. Thank you, mkeeter :)
