### ISSUE TITLE
Python3 fab module not loaded

### ISSUE THREAD

**Issue by sagitter** [mkeeter/antimony#136]
Hi all,

Python3 fab module cannot be imported when i try:

```
$ python3 -c 'import fab'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/fab/__init__.py", line 1, in <module>
    import fab.shapes as shapes
  File "/usr/lib/python3.4/site-packages/fab/shapes.py", line 5, in <module>
    from fab.types import Shape, Transform
  File "/usr/lib/python3.4/site-packages/fab/types.py", line 6, in <module>
    from _fabtypes import *
ImportError: No module named '_fabtypes'
```
```
/usr/lib/python3.4/site-packages/fab
/usr/lib/python3.4/site-packages/fab/__init__.py
/usr/lib/python3.4/site-packages/fab/__pycache__
/usr/lib/python3.4/site-packages/fab/__pycache__/__init__.cpython-34.pyc
/usr/lib/python3.4/site-packages/fab/__pycache__/__init__.cpython-34.pyo
/usr/lib/python3.4/site-packages/fab/__pycache__/shapes.cpython-34.pyc
/usr/lib/python3.4/site-packages/fab/__pycache__/shapes.cpython-34.pyo
/usr/lib/python3.4/site-packages/fab/__pycache__/types.cpython-34.pyc
/usr/lib/python3.4/site-packages/fab/__pycache__/types.cpython-34.pyo
/usr/lib/python3.4/site-packages/fab/shapes.py
/usr/lib/python3.4/site-packages/fab/types.py
```

antimony works but can ```fab``` module be used separately ?

**Comment by mkeeter** [comment]
At the moment, it's not possible to use the `fab` module outside of the application.

To do so, we'd have to compile the C / C++ sections of the module (named `_fabtypes`) into a `.dll` / `.dylib` / `.so`.  There's details about this in the [Boost documentation](http://www.boost.org/doc/libs/1_59_0/libs/python/doc/tutorial/doc/html/python/hello.html), among [other places](https://wiki.python.org/moin/boost.python/BuildingExtensions).

I'm not planning to make this a priority: the module only exposes the most basic functions, so you wouldn't be able to do anything interesting with the f-rep shapes (e.g. there aren't hooks for rendering).  If you'd like to extend the module with more hooks and make a stand-alone library, open up a discussion on the mailing list ([antimony-dev](https://groups.google.com/forum/#!forum/antimony-dev)).

For reference: in Antimony, we create this module [here](https://github.com/mkeeter/antimony/blob/develop/lib/fab/src/fab.cpp#L22-L67) and make it available for import [here](https://github.com/mkeeter/antimony/blob/develop/lib/fab/src/fab.cpp#L72-L75).
