### ISSUE TITLE
antimony packaged for Fedora

### ISSUE THREAD

**Issue by sagitter** [mkeeter/antimony#137]
Hi all,

```antimony``` is now distributed as [RPM](http://www.rpm.org/) in the [Fedora Project](https://getfedora.org/) 22/23 repositories.

If you want try them, install from Fedora by

```dnf install antimony --enablerepo=updates-testing```

Homepage of ```antimony``` RPMs in the Fedora package database: https://admin.fedoraproject.org/pkgdb/package/antimony/

Thanks to the developers which allow free sharing of this software.

**Comment by mkeeter** [comment]
Thanks!  I've added the package info to the README.
