### ISSUE TITLE
Sine functions

### ISSUE THREAD

**Issue by chalker7** [mkeeter/antimony#149]
I am trying to generate a 3 dimensional straight extrusion with a sine-wave shaped cross section (similar to the individual components seen in this picture: https://c2.staticflickr.com/4/3148/3102467395_8827b28d4b_z.jpg?zz=1) 
Is generating sine waves (preferably with a specified frequency, amplitude and number of periods) something that is possible in Antimony?

**Comment by mkeeter** [comment]
Yes, `sin` is a valid function that can be used in math strings.

Here's a simple example:

```py
import fab

title('sine wave demo')

input('f', float, 1)

# Create a sine wave and clip it within a bounding box
sine = (fab.types.Shape('=Y - sin(X * {f});'.format(**locals()))
        & fab.shapes.rectangle(-10, 10, -2, 1))

# Subtract out the same wave, shifted down a little bit
ribbon = sine & ~fab.shapes.move(sine, 0, -1)

output('s', ribbon)
```

...and the output:
<img width="557" alt="screen shot 2016-02-10 at 9 21 54 pm" src="https://cloud.githubusercontent.com/assets/745333/12968184/5787e74a-d03c-11e5-9a2b-89cd4eb42ab2.png">

**Comment by chalker7** [comment]
Beautiful, thanks so much!

**Comment by mkeeter** [comment]
You're welcome!
