### ISSUE TITLE
Installer for Windows 

### ISSUE THREAD

**Issue by SheepDomination** [mkeeter/antimony#150]
Is there not a installer for Windows ?

**Comment by mkeeter** [comment]
All of the components are theoretically cross-platform, but no one has gotten them to work together on Windows yet.  Please see [this issue](https://github.com/mkeeter/antimony/issues/71) for discussion.

**Comment by SheepDomination** [comment]
The instruction at the end of [this](https://github.com/mkeeter/antimony/blob/feature/win32-build/BUILDING.md#windows) page, basically compile it so that it can be used on Windows; or no ?

**Comment by mkeeter** [comment]
No one has gotten it working on Windows yet.  Those instructions are the beginning of my attempt, but without success.

**Comment by SheepDomination** [comment]
Bummer, thanks !
