### ISSUE TITLE
antimony-0.9.2/lib/fab/vendor/Eigen is bundled ?

### ISSUE THREAD

**Issue by sagitter** [mkeeter/antimony#163]
HI.

Are `antimony-0.9.2/lib/fab/vendor/Eigen/*` files original `Eigen` or a copy modified for Antimony ?

**Comment by mkeeter** [comment]
That's an unmodified Eigen release (not sure which one), included because it's a header-only library and makes for one fewer dependency.

In general, anything in a folder with the `vendor` prefix is an outside package.
