### ISSUE TITLE
"Save As" only present .sb format

### ISSUE THREAD

**Issue by pfelecan** [mkeeter/antimony#168]
I understood that when "saving as" we have the option to save the output in a different format than the native one, `.sb`, e.g., `.svg`

However, in **0.9.2** the only proposed format is `.sb`

Is this a missing feature or I wrongly understood what's possible?

**Comment by TLC123** [comment]
Saving As "DiffrentFileName".sameformat

**Comment by pfelecan** [comment]
Indeed. Mixed up with "Export".
