### ISSUE TITLE
Antimony crashes down always on application start up on Mac OSX 10.7.5

### ISSUE THREAD

**Issue by wielandrochel** [mkeeter/antimony#184]
Hi Matt,
here is my crash log. 
If you need any other Information so let me know.
Thank you very much for your time!
Regards Wieland

==============================

Process:         launchd [4506]
Path:            /Applications/Antimony.app/Contents/MacOS/Antimony
Identifier:      com.impraxical.antimony
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [244]

Date/Time:       2017-08-20 11:00:45.557 +0200
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          18926037 sec
Crashes Since Last Report:           25017
Per-App Crashes Since Last Report:   8
Anonymous UUID:                      85144D6E-D588-41AE-BC16-F2641468E8BB

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 1

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 19514
    thread_create: 0
    thread_set_state: 0

**Comment by mkeeter** [comment]
It looks like [Qt 5.6 only supports Mac OS 10.8](https://doc.qt.io/qt-5/supported-platforms-and-configurations.html#qt-5-6) or later.  You can try building it yourself and seeing whether that works, but I don't expect the pre-packaged app to work.
