### ISSUE TITLE
File / New => lost work

### ISSUE THREAD

**Issue by jflorian** [mkeeter/antimony#185]
Very new user here and I started work designing a knife block, based on things I learned in the video demo.  I wanted to see how to make one entity positioned relative to another, like having r1.x0 = r0.x1 + 1 but failed to imagine how that might be done.  An array would be nice, but the knifes are of varied size.  So, I figured I'd load up the example files and see if any hints might be found there.  Antimony warned me about lost work when attempting to File / Open, so I tried File / New figuring that I was just getting one more window on top of the original.  I then proceed to open the csg.sb example and knew I was already ahead of that from the excellent screencast.  I closed this to open another and to my surprise my original window and the work in it was now gone.  A loss of only a few minutes, but this is way too slick and polished to have that kind of glaring oversight, right?

**Comment by mkeeter** [comment]
Good catch, this should be fixed now if you want to pull + rebuild!
