### ISSUE TITLE
creating a language agnostic indirect CAD development platform

### ISSUE THREAD

**Issue by Foadsf** [mkeeter/antimony#186]
Dear antimony developers,

I just shared [this idea on the openSCAD repo](https://github.com/openscad/openscad/issues/2299), about developing a multi-language code based CAD development platform. I hope I can draw your attention to the idea. maybe you can join forces. 

Best.

**Comment by mkeeter** [comment]
Closing because there's no obvious next steps on how this applies to Antimony.
