### ISSUE TITLE
idea: non-causal visual CAD programing

### ISSUE THREAD

**Issue by Foadsf** [mkeeter/antimony#187]
In [this discussion](https://github.com/openscad/openscad/issues/2299) I asked @mkeeter why he chose Guile Language over for example Python for developing libfive/Ao. The advantages of  functional/declarative languages over imperative/scripting ones was pointed out to me by @doug-moen. It got me thinking about the limitations of the causal visual programing environments like SIMULINK and LabVIEW. They are limited when complicated nonlinear algebraic and differential equations need to be implemented. That's why [Modelica language](https://en.wikipedia.org/wiki/Modelica) was invented and Mathworks moved towards SimScape. There relations are defined between objects instead of the signals flowing through them in just one direction.
Specially for a CAD application there are geometrical constraints which philosophically can't be implemented in an state machine narrative. For example the parallel-ness of two lines is not a directional concept. it is a (non)linear equation. 

I was thinking maybe a similar concept as Modelica language and it's visual programing environments like [OpenModelica](https://en.wikipedia.org/wiki/OpenModelica), could be adopted for visual CAD development like Antimony. for example every box/object to have connectors on top and bottom as well. For instance: two points can have a distance. two lines can be parallel or skew plus a distance, a point and a line can have a distance, two faces can have an angle or being parallel plus a distance.... these relations could be represented as vertical pipes in the visual environment and, nonlinear system of equations to be solved in the background. There can be a set of relations between different classes and when implemented a system of algebraic equations will be solved.

**Comment by mkeeter** [comment]
Closing this, as this doesn't makes sense in my roadmap for Antimony.  @Foadsf – as always, contributions are welcome.
