### ISSUE TITLE
STL export misses subtraction of extruded text

### ISSUE THREAD

**Issue by kromanenko** [mkeeter/antimony#200]
Tried to export to STL model of label table with carved (by subtraction) text.
While model in viewport and height-map image both has carved text, the STL-exported model looks like flat table without carving.

Zipped graph file, height map and zipped STL are attached.

[label.sb.txt](https://github.com/mkeeter/antimony/files/2489131/label.sb.txt)
![height-map](https://user-images.githubusercontent.com/10499375/47114410-ca789080-d26c-11e8-858b-5d6481af2067.png)
[antimony.stl.zip](https://github.com/mkeeter/antimony/files/2489138/antimony.stl.zip)

Environment:
Binary installation on Mac OS Mojave.
Release: 0.9.3 
Git revision: 020910c

**Comment by mkeeter** [comment]
Have you tried increasing the mesh resolution?  I'd be suspicious that the thin text is just missed by the meshing sampling grid.

**Comment by kromanenko** [comment]
Btw, your viewer works fine!
<img width="712" alt="screen shot 2018-10-18 at 11 32 49 pm" src="https://user-images.githubusercontent.com/10499375/47179132-4dadeb00-d32e-11e8-96ad-dd0bb68fc3f2.png">
