### ISSUE TITLE
Linux fresh compilation issues

### ISSUE THREAD

**Issue by Silent-Ash** [mkeeter/antimony#206]
1. Please, add libqt5opengl5 to the Linux Install dependencies, line 46 of BUILDING.md. "cmake -GNinja .." command lacks some two qt5OpenGL config files.

Installing apt-get recommended libqt5opengl5-dev solves the problem.

2. Please, modify "ninja" invocation, line 58 of BUILDING.md. Default invocation cause OS freeze forever with logical shortcut circuit overheating processor, so only switching computer off can help.

Limiting ninja job count to 1 solves the problem. "ninja -j 1" works pretty fast and well.

Thank You.

Computer: Lenovo Z580 notebook
System:    Host: mate Kernel: 4.15.0-65-generic x86_64 bits: 64 Desktop: MATE 1.22.0 Distro: Linux Mint 19.2 Tina

**Comment by mkeeter** [comment]
1.  I've added a note about that dependency, thanks!
2.  If your computer overheats and shuts down when compiling a job using multiple processes, this is very much not Antimony's or `ninja`'s fault.  Using multiple processes makes building faster, so I'm not going to recommend against it.
