### ISSUE TITLE
Backport to QT 5.3?

### ISSUE THREAD

**Issue by astronouth7303** [mkeeter/antimony#23]
Would it be possible to backport antimony to QT 5.3?

My use case is that Debian only has QT 5.4 under experimental (not testing, not unstable). And while I would like very much to try antimony, even having to compile it, I don't want to have to:

* Create an account to download an SDK for the GUI toolkit for the program I want to try
* Attempt to juggle the sources required to import a handful of packages from experimental (it's blown up on me before)

**Comment by mkeeter** [comment]
Antimony is using Qt's newer OpenGL API, which requires Qt 5.4.

Qt's account creation step is silly, but you can use the [offline installers](http://www.qt.io/download-open-source/#section-3) and skip it entirely.

I've updated the BUILDING guide to link directly to the offline installers.
