### ISSUE TITLE
Windows 10 version

### ISSUE THREAD

**Issue by JuanJ67m** [mkeeter/antimony#231]
Where is the windows 10 version?

**Comment by JuanJ67m** [comment]
please, add support for AutoCAD AutoLISP

**Comment by JuanJ67m** [comment]
https://www.theswamp.org/index.php?topic=56631.0

**Comment by MatthewMiguelHernandez** [comment]
@JuanJ67m There is a build guide for Windows 10.
https://github.com/mkeeter/antimony/blob/develop/BUILDING.md#windows-experimental

**Comment by mkeeter** [comment]
Yup, that's the relevant link!

I'm not going to add support for AutoCAD AutoLISP, but if you want to get your Scheme on, check out my [current project](https://libfive.com/studio).
