### ISSUE TITLE
suggestion: change default Add menu keybinding

### ISSUE THREAD

**Issue by xxv** [mkeeter/antimony#30]
`Shift+A` is good, but not great. Perhaps a cue could be borrowed from Blender and the spacebar could bring up the add menu? right-click (I know, many mac users)? I find it a bit tedious to add a bunch of things and faster access to add could help a ton.

**Comment by joshuashort** [comment]
I assumed right-click would work.. even Mac users are ok with this ;)
It seems natural for a 'right-click' or 'two-finger click' to bring up a menu..

**Comment by astronouth7303** [comment]
+1 Right click

**Comment by joshuashort** [comment]
I forked and modified viewport.cpp and canvas.cpp to show the add menu when right clicking; it's basically copy-pasta from the keyPressEvent; it'd probably be best to create some kind of show-menu-helper-function, but this does work for now. I'll submit a pull request, if you want it. I haven't done this before, so hopefully it goes well.

**Comment by mgold** [comment]
+1 Right click (Mac user)

**Comment by astronouth7303** [comment]
Fixed by #42
