### ISSUE TITLE
Linking error in develop

### ISSUE THREAD

**Issue by astronouth7303** [mkeeter/antimony#39]
It seems that it's no longer linking in boost in d2ad474 on my system. ([Partial build log](http://paste2.org/x76m3Ep4))

My build process is:
```
$ make clean
$ rm -r *
$ ~/.local/Qt5.4.1/5.4/gcc_64/bin/qmake ../qt/antimony.pro && make 
```

I've made no changes to the project.

**Comment by mkeeter** [comment]
I suspect that f952d20b290c42e4c4cb65f29c126832be246c82 is the culprit.  Can you run `ldconfig -p|grep python` and see what boost::python is named?  Right now, I check for `libboost_python-py34.so` and `libboost_python3.so`, using whichever one is present.

**Comment by astronouth7303** [comment]
Ah, that would be the problem. For whatever reason, `ldconfig` is under `/sbin`, which is only on the path when you're root.

I'm not certain if this is a bug with Debian testing or a misuses of `ldconfig` on the part of `qmake`.

**Comment by astronouth7303** [comment]
So `antimony.pro` uses `ldconfig` to detect how `boost::python` is installed. (This appears to be a Debian/Ubuntu vs Arch & Fedora thing.)

Arch installs `ldconfig` in `/usr/bin`. Ubuntu and Debian install it in `/sbin`. Fedora has it in `/sbin`.

**Comment by mkeeter** [comment]
This looks like it's an issue with the default `$PATH` variable.  It works fine with Ubuntu because `/sbin` is [in the default path](http://askubuntu.com/questions/386629/what-are-the-default-path-values).

Is Debian testing doing something different with `$PATH`?

**Comment by astronouth7303** [comment]
Debian only has `/sbin` in the PATH if you're root.

**Comment by astronouth7303** [comment]
Crowdsourced answer for Fedora: `/sbin` is on the path by default.

**Comment by mkeeter** [comment]
Okay, want to try ace33e00a62393b7cc157e836875aebcaba55cf5?  The Linux build is getting a bit hairy, but it should now look for `ldconfig` if it's not on the path by default.

**Comment by astronouth7303** [comment]
(For completeness, Arch also has `/sbin` on the PATH.)

**Comment by astronouth7303** [comment]
Yup, builds now. Thank you!

(I think this is why GNU configure generally takes the approach of "build a bunch of test programs and see which ones compile".)
