### ISSUE TITLE
Fails to compile on Windows/Cygwin

### ISSUE THREAD

**Issue by paul70078** [mkeeter/antimony#47]
I tried to compile it on Windows with cygwin, but I get errors when executing "make -j8".
There is a massice amount of undefined references.
I used the 0.7.9 release.
LOG: http://pastebin.com/PwYALc4a

**Comment by mkeeter** [comment]
This looks like a missing boost::python3.  Have you talked to the fellow doing [this PR](https://github.com/mkeeter/antimony/pull/43)?

**Comment by paul70078** [comment]
Now it compiles. Thanks
