### ISSUE TITLE
Suggestion: Easier node connection

### ISSUE THREAD

**Issue by Highstaker** [mkeeter/antimony#50]
When I need to connect nodes I have to hit this little cube on the node, which can be pretty hard, and then I need to drag the mouse and hit the input of another node exactly. This is pretty tedious.

The demo video shows snapping, but how can I do this.

Also, is it possible to make outputs and inputs bigger so they would be easier to click?

Another suggestion is, when I drag the mouse from node 1, I could hover over not only the cube representing the input on node 2, but also the name of the input or its value, so it would connect. Right now it connects only if i hover over the input cube.

Thanks ;)

~High

**Comment by astronouth7303** [comment]
Space bar causes it to snap.

+1 for more useful snapping

**Comment by astronouth7303** [comment]
Moved to wishlist thread on the mailing list.

**Comment by Highstaker** [comment]
Ah, thank you for the tip!

Heh, I've just discovered an instruction manual in docs XD
