### ISSUE TITLE
Save Dialog does not add .sb

### ISSUE THREAD

**Issue by astronouth7303** [mkeeter/antimony#56]
If you type in a file name without the `.sb` extension in the Save As file select dialog, it is not added.

This makes the file unlisted by default when you go to Open it.

I think this is in [`App::onSaveAs`](https://github.com/mkeeter/antimony/blob/5dc28428dbd7a8e861d11c08b524b14916ac3d2b/src/app/app.cpp#L150).

**Comment by mkeeter** [comment]
This looks specific to Linux -- it works correctly on Mac.
