### ISSUE TITLE
node visibility

### ISSUE THREAD

**Issue by toomuchcookies** [mkeeter/antimony#73]
Thanks again. Just as a suggestion towards a better 3d view. I know, that i can 'Hide UI', which hides all the outlines and drag points, but it would be nice, if one could also specify which ui-handles to view or hide. 

As an Inspiration houdini (sideeffects) has a node system, where for each node, you can chose if you want to show it in the preview and/or in the final render. In the case of antimony we would be able to chose if we wanted to show the handles (ui) and/or the final geometry. This way, it would be easier to work on some small feature, while the big geometry around it is hidden.

**Comment by astronouth7303** [comment]
Already on the wish list from #61.
