### ISSUE TITLE
Right Triangles and negative values

### ISSUE THREAD

**Issue by toomuchcookies** [mkeeter/antimony#74]
The software is doing strange and unexpected things when i select negative values for width/height of a right angle node. See example:

Everything working nicely:
![antimony 1 2](https://cloud.githubusercontent.com/assets/373859/8018711/0b1f9fdc-0c2a-11e5-82be-28554b7c8165.png)

One negative value:
![antimony -1 2](https://cloud.githubusercontent.com/assets/373859/8018709/0b1d943a-0c2a-11e5-89ea-5e527f43b948.png)
![antimony 1 -2](https://cloud.githubusercontent.com/assets/373859/8018710/0b1f2160-0c2a-11e5-971d-ffccc9509b73.png)

Both values negative:
![antimony -1 -2](https://cloud.githubusercontent.com/assets/373859/8018708/0b1d0286-0c2a-11e5-9046-9b840eb22942.png)

**Comment by astronouth7303** [comment]
I'm not sure the bug here is allowing negative values here or producing an infinite object when you do.
