### ISSUE TITLE
Is it possible to compile this under QT5.3?

### ISSUE THREAD

**Issue by kengdahl** [mkeeter/antimony#94]
I'm stuck with Debian and would very much like to install antimony on this computer. 

Thank you for making such a innovative piece of software.

**Comment by mkeeter** [comment]
No, because Antimony uses the long-awaited newer OpenGL API (`QOpenGLWidget` rather than `QGLWidget`).  Qt has installers [available for download](http://www.qt.io/download-open-source/#section-3).  I do Linux development on Ubuntu, which is also stuck on 5.3, but the installer works fine.
